This is an interface for Notebook Editor ..
Notebook = Code + Output + documenttaion

In [1]:
print ("Welcome to Azure Machine Learning")

Welcome to Azure Machine Learning

In [2]:
print ("Welcome to Azure Machine Learning  and This is JupyterLab ...")

Welcome to Azure Machine Learning  and This is JupyterLab ...

In [3]:
import pandas as pd
import numpy as np
import sklearn
import matplotlib.pyplot as plt


print("Libraries loaded successfully")

Libraries loaded successfully

These libraries are used for Data Processing, Machine Learning and Visualization ...

In [6]:
!pip install seaborn

Requirement already satisfied: seaborn in /anaconda/envs/azureml_py38/lib/python3.10/site-packages (0.13.2)
Requirement already satisfied: numpy!=1.24.0,>=1.20 in /anaconda/envs/azureml_py38/lib/python3.10/site-packages (from seaborn) (1.23.5)
Requirement already satisfied: pandas>=1.2 in /anaconda/envs/azureml_py38/lib/python3.10/site-packages (from seaborn) (1.5.3)
Requirement already satisfied: matplotlib!=3.6.1,>=3.4 in /anaconda/envs/azureml_py38/lib/python3.10/site-packages (from seaborn) (3.7.1)
Requirement already satisfied: contourpy>=1.0.1 in /anaconda/envs/azureml_py38/lib/python3.10/site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (1.3.2)
Requirement already satisfied: cycler>=0.10 in /anaconda/envs/azureml_py38/lib/python3.10/site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /anaconda/envs/azureml_py38/lib/python3.10/site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (4.51.0)
Requirement already satisfied: kiwisolver>=1.0.1 in /anaconda/envs/azureml_py38/lib/python3.10/site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (1.4.9)
Requirement already satisfied: packaging>=20.0 in /anaconda/envs/azureml_py38/lib/python3.10/site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (25.0)
Requirement already satisfied: pillow>=6.2.0 in /anaconda/envs/azureml_py38/lib/python3.10/site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (9.2.0)
Requirement already satisfied: pyparsing>=2.3.1 in /anaconda/envs/azureml_py38/lib/python3.10/site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (3.2.5)
Requirement already satisfied: python-dateutil>=2.7 in /anaconda/envs/azureml_py38/lib/python3.10/site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /anaconda/envs/azureml_py38/lib/python3.10/site-packages (from pandas>=1.2->seaborn) (2022.5)
Requirement already satisfied: six>=1.5 in /anaconda/envs/azureml_py38/lib/python3.10/site-packages (from python-dateutil>=2.7->matplotlib!=3.6.1,>=3.4->seaborn) (1.17.0)

In [7]:
import seaborn as sns

print ("Seaborn Installed")

Seaborn Installed

In [8]:
from azureml.core import workspace

print (workspace.name, workspace.resource_group, workspace.location)

AttributeError: module 'azureml.core.workspace' has no attribute 'name'

In [2]:
from azureml.core import Workspace

ws = Workspace.from_config()

print (ws.name, ws.resource_group, ws.location)

ajit-dp100 ajit-rg centralindia

# LAB 1 --  Data Loading and Basic Exploration using Pandas

# Pandas -- Data Manipulation -- Data Loading and Exploration ..

# Load Dataset, View Top Rows, Check Data Types, Summary statistics

In [12]:
import pandas as pd

df = pd.read_csv('diabetes.csv')

In [7]:
! ls

'Untitled Folder'   Users   ajit_demo   diabetes.csv   dp100-first-nb.ipynb

In [16]:
df.head()

# Represents first five rows of your dataset

,PatientID,Pregnancies,PlasmaGlucose,DiastolicBloodPressure,TricepsThickness,SerumInsulin,BMI,DiabetesPedigree,Age,Diabetic
0,1354778,0,171,80,34,23,43.509726,1.213191,21,0
1,1147438,8,92,93,47,36,21.240576,0.158365,23,0
2,1640031,7,115,47,52,35,41.511523,0.079019,23,0
3,1883350,9,103,78,25,304,29.582192,1.282870,43,1
4,1424119,1,85,59,27,35,42.604536,0.549542,22,0

In [17]:
df.info()

# Detect null values and data types

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 10 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   PatientID               10000 non-null  int64
 1   Pregnancies             10000 non-null  int64
 2   PlasmaGlucose           10000 non-null  int64
 3   DiastolicBloodPressure  10000 non-null  int64
 4   TricepsThickness        10000 non-null  int64
 5   SerumInsulin            10000 non-null  int64
 6   BMI                     10000 non-null  float64
 7   DiabetesPedigree        10000 non-null  float64
 8   Age                     10000 non-null  int64
 9   Diabetic                10000 non-null  int64
dtypes: float64(2), int64(8)
memory usage: 781.4 KB

In [18]:
df.describe()

# Better statistical understanding

,PatientID,Pregnancies,PlasmaGlucose,DiastolicBloodPressure,TricepsThickness,SerumInsulin,BMI,DiabetesPedigree,Age,Diabetic
count,1.000000e+04,10000.00000,10000.000000,10000.000000,10000.00000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000
mean,1.502122e+06,3.25580,107.850200,71.207500,28.81760,139.243600,31.567022,0.400944,30.134100,0.334400
std,2.892868e+05,3.40572,31.920909,16.801478,14.50648,133.777919,9.804366,0.381463,12.106047,0.471804
min,1.000038e+06,0.00000,44.000000,24.000000,7.00000,14.000000,18.200807,0.078044,21.000000,0.000000
25%,1.251672e+06,0.00000,84.000000,58.000000,15.00000,39.000000,21.247427,0.137065,22.000000,0.000000
50%,1.504394e+06,2.00000,105.000000,72.000000,31.00000,85.000000,31.922421,0.199698,24.000000,0.000000
75%,1.754608e+06,6.00000,129.000000,85.000000,41.00000,197.000000,39.328921,0.621158,35.000000,1.000000
max,1.999997e+06,14.00000,192.000000,117.000000,92.00000,796.000000,56.034628,2.301594,77.000000,1.000000

In [21]:
df.shape

# To find out rows and colums in dataset

(10000, 10)

# It is used in EDA (Exploratory Data Analysis)